# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-13 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200513_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PermissionPack', to='auth.Permission', verbose_name='permission'),
        ),
    ]
