# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-13 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200513_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenttypes',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='group',
        ),
        migrations.RemoveField(
            model_name='permissions',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user',
        ),
        migrations.DeleteModel(
            name='ContentTypes',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.DeleteModel(
            name='Permissions',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
